package UI;

import dao.daoEvento;
import java.awt.Color;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;
import static dao.myConnection.*;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.PreparedStatement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jasot
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() throws UnknownHostException {
        try {
            String hostName = InetAddress.getLocalHost().getHostName();
            initComponents();
            panelUniverso.setVisible(false);
            panelHome.setVisible(true);
            String serverName[] = {hostName, "SQLEXPRESS"};
            Connection con = ConnectToDatabase(serverName);
            ResultSet rs = con.getMetaData().getCatalogs();
            while (rs.next()) {
                System.out.println(rs.getString(1));
            }
            System.out.println("");
            PreparedStatement ps = con.prepareStatement("SELECT\n"
                    + "            SERVERPROPERTY('MachineName') AS [ServerName], \n"
                    + "			SERVERPROPERTY('ServerName') AS [ServerInstanceName], \n"
                    + "            SERVERPROPERTY('InstanceName') AS [Instance], \n"
                    + "            SERVERPROPERTY('Edition') AS [Edition],\n"
                    + "            SERVERPROPERTY('ProductVersion') AS [ProductVersion], \n"
                    + "			Left(@@Version, Charindex('-', @@version) - 2) As VersionName");
            ResultSet rs2 = ps.executeQuery();
            cmbBoxServers.removeAllItems();
            while (rs2.next()) {
                System.out.println(rs2.getString(1));
                System.out.println(rs2.getString(2));
                cmbBoxServers.addItem(rs2.getString(2));
                System.out.println(rs2.getString(3));
            }
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelUniverso = new javax.swing.JPanel();
        panelAcciones = new javax.swing.JPanel();
        panelProduction = new javax.swing.JPanel();
        panelPerson = new javax.swing.JPanel();
        panelSales = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelMenu = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnSales = new javax.swing.JButton();
        btnProduction = new javax.swing.JButton();
        btnPerson = new javax.swing.JButton();
        panelHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnQuery = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        cmbBoxServers = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new java.awt.CardLayout());

        panelUniverso.setBackground(new java.awt.Color(1, 86, 118));
        panelUniverso.setMaximumSize(new java.awt.Dimension(700, 500));
        panelUniverso.setMinimumSize(new java.awt.Dimension(700, 500));
        panelUniverso.setPreferredSize(new java.awt.Dimension(700, 500));
        panelUniverso.setRequestFocusEnabled(false);
        panelUniverso.setLayout(new java.awt.BorderLayout());

        panelAcciones.setBackground(new java.awt.Color(1, 86, 118));
        panelAcciones.setMaximumSize(new java.awt.Dimension(700, 430));
        panelAcciones.setMinimumSize(new java.awt.Dimension(700, 430));
        panelAcciones.setPreferredSize(new java.awt.Dimension(700, 430));
        panelAcciones.setLayout(new java.awt.CardLayout());

        panelProduction.setBackground(new java.awt.Color(1, 86, 118));
        panelProduction.setForeground(new java.awt.Color(0, 0, 0));
        panelProduction.setMaximumSize(new java.awt.Dimension(700, 430));
        panelProduction.setMinimumSize(new java.awt.Dimension(700, 430));
        panelProduction.setPreferredSize(new java.awt.Dimension(700, 430));

        javax.swing.GroupLayout panelProductionLayout = new javax.swing.GroupLayout(panelProduction);
        panelProduction.setLayout(panelProductionLayout);
        panelProductionLayout.setHorizontalGroup(
            panelProductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        panelProductionLayout.setVerticalGroup(
            panelProductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        panelAcciones.add(panelProduction, "card3");

        panelPerson.setBackground(new java.awt.Color(1, 86, 118));
        panelPerson.setForeground(new java.awt.Color(0, 0, 0));
        panelPerson.setMaximumSize(new java.awt.Dimension(700, 430));
        panelPerson.setMinimumSize(new java.awt.Dimension(700, 430));
        panelPerson.setPreferredSize(new java.awt.Dimension(700, 430));

        javax.swing.GroupLayout panelPersonLayout = new javax.swing.GroupLayout(panelPerson);
        panelPerson.setLayout(panelPersonLayout);
        panelPersonLayout.setHorizontalGroup(
            panelPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        panelPersonLayout.setVerticalGroup(
            panelPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        panelAcciones.add(panelPerson, "card4");

        panelSales.setBackground(new java.awt.Color(1, 86, 118));
        panelSales.setForeground(new java.awt.Color(0, 0, 0));
        panelSales.setMaximumSize(new java.awt.Dimension(700, 430));
        panelSales.setMinimumSize(new java.awt.Dimension(700, 430));
        panelSales.setPreferredSize(new java.awt.Dimension(700, 430));
        panelSales.setLayout(new java.awt.GridBagLayout());

        btnSave.setBackground(new java.awt.Color(0, 153, 153));
        btnSave.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 0, 0));
        btnSave.setText("Guardar");
        btnSave.setBorderPainted(false);
        btnSave.setMaximumSize(new java.awt.Dimension(90, 40));
        btnSave.setMinimumSize(new java.awt.Dimension(90, 40));
        btnSave.setPreferredSize(new java.awt.Dimension(90, 40));
        btnSave.setRequestFocusEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(318, 80, 0, 51);
        panelSales.add(btnSave, gridBagConstraints);

        jCheckBox1.setText("Country");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(6, 40, 0, 0);
        panelSales.add(jCheckBox1, gridBagConstraints);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 419;
        gridBagConstraints.ipady = 339;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 40, 25, 0);
        panelSales.add(jScrollPane1, gridBagConstraints);

        panelAcciones.add(panelSales, "card2");

        panelUniverso.add(panelAcciones, java.awt.BorderLayout.CENTER);

        panelMenu.setBackground(new java.awt.Color(1, 86, 118));
        panelMenu.setForeground(new java.awt.Color(204, 204, 0));
        panelMenu.setMaximumSize(new java.awt.Dimension(700, 70));
        panelMenu.setMinimumSize(new java.awt.Dimension(700, 70));
        panelMenu.setName(""); // NOI18N
        panelMenu.setPreferredSize(new java.awt.Dimension(700, 70));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10);
        flowLayout1.setAlignOnBaseline(true);
        panelMenu.setLayout(flowLayout1);

        btnInicio.setBackground(new java.awt.Color(255, 255, 255));
        btnInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/home_icon.png"))); // NOI18N
        btnInicio.setBorderPainted(false);
        btnInicio.setMaximumSize(new java.awt.Dimension(80, 50));
        btnInicio.setMinimumSize(new java.awt.Dimension(80, 50));
        btnInicio.setPreferredSize(new java.awt.Dimension(80, 50));
        btnInicio.setRequestFocusEnabled(false);
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        panelMenu.add(btnInicio);

        btnSales.setBackground(new java.awt.Color(255, 255, 255));
        btnSales.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnSales.setForeground(new java.awt.Color(0, 0, 0));
        btnSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/sales_icon_2_1.png"))); // NOI18N
        btnSales.setText("Sales");
        btnSales.setBorderPainted(false);
        btnSales.setMaximumSize(new java.awt.Dimension(115, 50));
        btnSales.setMinimumSize(new java.awt.Dimension(115, 50));
        btnSales.setPreferredSize(new java.awt.Dimension(115, 50));
        btnSales.setRequestFocusEnabled(false);
        btnSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesActionPerformed(evt);
            }
        });
        panelMenu.add(btnSales);

        btnProduction.setBackground(new java.awt.Color(255, 255, 255));
        btnProduction.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnProduction.setForeground(new java.awt.Color(0, 0, 0));
        btnProduction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/production_icon_2.png"))); // NOI18N
        btnProduction.setText(" Production");
        btnProduction.setBorderPainted(false);
        btnProduction.setMaximumSize(new java.awt.Dimension(165, 50));
        btnProduction.setMinimumSize(new java.awt.Dimension(165, 50));
        btnProduction.setPreferredSize(new java.awt.Dimension(165, 50));
        btnProduction.setRequestFocusEnabled(false);
        btnProduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductionActionPerformed(evt);
            }
        });
        panelMenu.add(btnProduction);

        btnPerson.setBackground(new java.awt.Color(255, 255, 255));
        btnPerson.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnPerson.setForeground(new java.awt.Color(0, 0, 0));
        btnPerson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/person_icon_2.png"))); // NOI18N
        btnPerson.setText("Person");
        btnPerson.setBorderPainted(false);
        btnPerson.setMaximumSize(new java.awt.Dimension(135, 50));
        btnPerson.setMinimumSize(new java.awt.Dimension(135, 50));
        btnPerson.setPreferredSize(new java.awt.Dimension(135, 50));
        btnPerson.setRequestFocusEnabled(false);
        btnPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonActionPerformed(evt);
            }
        });
        panelMenu.add(btnPerson);

        panelUniverso.add(panelMenu, java.awt.BorderLayout.NORTH);

        getContentPane().add(panelUniverso, "card2");

        panelHome.setBackground(new java.awt.Color(0, 51, 71));
        panelHome.setMaximumSize(new java.awt.Dimension(700, 500));
        panelHome.setMinimumSize(new java.awt.Dimension(700, 500));
        panelHome.setPreferredSize(new java.awt.Dimension(700, 500));
        panelHome.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 221, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/database_tool_3.png"))); // NOI18N
        jLabel1.setText("OLAP Tool");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jLabel1.setIconTextGap(15);
        jLabel1.setMaximumSize(new java.awt.Dimension(700, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(700, 100));
        jLabel1.setPreferredSize(new java.awt.Dimension(700, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = -295;
        gridBagConstraints.ipady = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(105, 142, 0, 153);
        panelHome.add(jLabel1, gridBagConstraints);

        btnQuery.setBackground(new java.awt.Color(255, 255, 255));
        btnQuery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/consulta.png"))); // NOI18N
        btnQuery.setToolTipText("");
        btnQuery.setMaximumSize(new java.awt.Dimension(40, 40));
        btnQuery.setMinimumSize(new java.awt.Dimension(40, 40));
        btnQuery.setPreferredSize(new java.awt.Dimension(40, 40));
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(28, 487, 87, 0);
        panelHome.add(btnQuery, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(0, 51, 71));

        jPanel2.setBackground(new java.awt.Color(0, 51, 71));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Server: ");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Database: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 32, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel2);

        jPanel1.setBackground(new java.awt.Color(0, 51, 71));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setMaximumSize(new java.awt.Dimension(65, 26));

        cmbBoxServers.setBackground(new java.awt.Color(255, 255, 255));
        cmbBoxServers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBoxServers.setMaximumSize(new java.awt.Dimension(65, 26));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmbBoxServers, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cmbBoxServers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(6, 6, 6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(31, 169, 0, 0);
        panelHome.add(jPanel3, gridBagConstraints);

        getContentPane().add(panelHome, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductionActionPerformed
        panelPerson.setVisible(false);
        panelSales.setVisible(false);
        panelProduction.setVisible(true);
    }//GEN-LAST:event_btnProductionActionPerformed

    private void btnSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesActionPerformed
        panelProduction.setVisible(false);
        panelPerson.setVisible(false);
        panelSales.setVisible(true);
    }//GEN-LAST:event_btnSalesActionPerformed

    private void btnPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonActionPerformed
        panelProduction.setVisible(false);
        panelSales.setVisible(false);
        panelPerson.setVisible(true);
    }//GEN-LAST:event_btnPersonActionPerformed

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        panelUniverso.setVisible(false);
        panelHome.setVisible(true);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed
        ConnectToDatabase(cmbBoxServers.getSelectedItem().toString().split("\\\\"));
            panelHome.setVisible(false);
            panelUniverso.setVisible(true);
    }//GEN-LAST:event_btnQueryActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            Connection con = ConnectToDatabase(cmbBoxServers.getSelectedItem().toString().split("\\\\"));
                new daoEvento().insert(con);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            if (false) {
                javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
            } else {
                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        System.out.println(info.getName());                    
                    }
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Windows".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

//</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MenuPrincipal().setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnPerson;
    private javax.swing.JButton btnProduction;
    private javax.swing.JButton btnQuery;
    private javax.swing.JButton btnSales;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbBoxServers;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelAcciones;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPerson;
    private javax.swing.JPanel panelProduction;
    private javax.swing.JPanel panelSales;
    private javax.swing.JPanel panelUniverso;
    // End of variables declaration//GEN-END:variables
}
